name: HelloWorld Branch
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world Echo step
        run: echo "Hello, world from the develop branch!"